In [ ]:
import os
import sys
sys.path.insert(1, r'D:\Khabarov\Репозиторий\sql_premises_and_volumes')
from Helpers.ParamsAndFuns import ParamsAndFuns as p
import numpy as np
import pandas as pd
from Helpers.VolumesHelper import VolumesHelper
# p.set_np_pd_opts()


source_path = r'D:\Khabarov\Репозиторий\sql_premises_and_volumes\SourceData\ИсходныеДанныеАрматура1.xlsx' #Здесь укажи путь к табл
volHel = VolumesHelper(source_path=source_path)
dfFull = volHel.fullDf

#=====Запусти для загрузки данных=====

In [ ]:
#=====Запусти для выгрузки номенклатуры=====
directory = r'D:\Khabarov\Репозиторий\sql_premises_and_volumes\Data'
volHel.save_nomenclature(source_path=source_path,directory=directory)

In [ ]:
#=====Запусти для выгрузки данных по проценту радиаторов стандартных размеров=====
directory = r'D:\Khabarov\Репозиторий\sql_premises_and_volumes\Data'
volHel.save_radiators_percentage_sheet(directory=directory)

In [ ]:
volHel.get_floor_types_features_by_columns()
#Получение датасета по этажам секций (по пилонам)

In [ ]:
volHel.save_prefab_nomenclature(directory=directory)
#Для номенклатуры префаба

In [ ]:
volHel.save_second_facade(directory=directory)
#Для загрузки второго фасада

In [ ]:
volHel.save_radiators_nomenclature(directory=directory)
#Для сохранения радиаторов

## На удаление

In [1]:
from Helpers.DbConnector import DbConnector
import pandas as pd

dbcon = DbConnector()
dbcon

Подключено

In [8]:
tower_morphotypes = ['B_50T5.8_Шаг 6.9', 'B_50T6.8_Шаг 6.9', 'B_50T7.8_Шаг 6.9', 
        'B_50TS(TN)3,5/4_Шаг 6.9', 'B_75T7.8_Шаг 6.9', 'B_75T8.8_Шаг 6.9', 
        'C_100T8.8_Шаг 6.9', 'C_50T5.8_Шаг 6.9', 'C_50T6.8_Шаг 6.9', 
        'C_50TS(TN)4.8_Шаг 6.9', 'C_50TS(TN)5.11_Шаг 6.9', 'C_50TS(TN)6.10_Шаг 6.9', 
        'C_75T7.8_Шаг 6.9', 'C_75T8.8_Шаг 6.9', 'C_75TS(TN)7.11_Шаг 6.9', 
        'C_75TS(TN)7.12_Шаг 6.9', 'С_50_6.10_Шаг 6.9', 'С_50_6.8_Шаг 6.9', 
        'С_75TS(TN)6.10_Шаг 6.9', 'D_50TS(TN)6.8_Шаг 3.45']

In [2]:
engine = dbcon.engine
engine

Engine(postgresql://n.khabarov:***@172.16.250.156:4032/validator)

In [4]:
myQuery = """
SELECT 
    sections.construction_object_id,
    sections."Секция",
    floors."Этаж",
    sections."Морфотип",
    floors."Тип_этажа"
FROM
    (SELECT 
        cof.construction_object_section_id,
        cof.title AS "Этаж",
        ft.title AS "Тип_этажа"
     FROM "validator".sections.construction_object_floors cof 
     LEFT JOIN "validator".dict.floor_types ft ON cof.floor_type_id = ft.floor_type_id 
    ) AS floors
LEFT JOIN
    (SELECT 
        cos2.construction_object_id,
        cos2.construction_object_section_id,
        cos2.title AS "Секция",
        st.title AS "Морфотип"
     FROM "validator".sections.construction_object_sections cos2 
     LEFT JOIN "validator".dict.section_types st ON cos2.section_type_id = st.section_type_id
    ) AS sections ON floors.construction_object_section_id = sections.construction_object_section_id
"""

# Выполнение запроса
df_floors_sections = pd.read_sql_query(myQuery, con=engine)

,construction_object_id,Секция,Этаж,Морфотип,Тип_этажа
0,0b4aa853-21e6-4216-bb7e-f021698143ef,Секция 2,Этаж -01,С_CS(CN)7.10_Шаг 3.45,-1 этаж
1,780ea05e-3410-41ed-889d-33fbd3a36503,Секция 1,Этаж -01,B_CS(CN)5.8_Шаг 3.45,-1 этаж
2,780ea05e-3410-41ed-889d-33fbd3a36503,Секция 1,Этаж 01,B_CS(CN)5.8_Шаг 3.45,1 этаж
3,780ea05e-3410-41ed-889d-33fbd3a36503,Секция 1,Этаж 02,B_CS(CN)5.8_Шаг 3.45,Типовой этаж
4,780ea05e-3410-41ed-889d-33fbd3a36503,Секция 2,Этаж -01,B_50TS(TN)5.10_Шаг 3.45,-1 этаж
...,...,...,...,...,...
14734,0b4aa853-21e6-4216-bb7e-f021698143ef,Секция 1,Этаж 06,C_EW(NS)8.4_Шаг 3.45,Типовой этаж
14735,0b4aa853-21e6-4216-bb7e-f021698143ef,Секция 1,Этаж 07,C_EW(NS)8.4_Шаг 3.45,Типовой этаж
14736,0b4aa853-21e6-4216-bb7e-f021698143ef,Секция 1,Этаж 08,C_EW(NS)8.4_Шаг 3.45,Типовой этаж
14737,0b4aa853-21e6-4216-bb7e-f021698143ef,Секция 1,Этаж 09,C_EW(NS)8.4_Шаг 3.45,Верхний этаж
14738,0b4aa853-21e6-4216-bb7e-f021698143ef,Секция 1,Этаж 10,C_EW(NS)8.4_Шаг 3.45,Тех.этаж

In [19]:
df_sect_floors_max = df_floors_sections.groupby(['construction_object_id','Секция'],as_index=False).agg(Кол_во_этажей=('Этаж','count'),Морфотип=('Морфотип','first'))
objects_with_towers = df_sect_floors_max[
    (df_sect_floors_max['Кол_во_этажей'] > 16)
    & (df_sect_floors_max['Морфотип'].isin(tower_morphotypes))
    ]['construction_object_id'].unique()
objects_with_towers

array([UUID('1ef13c96-09be-45e6-8279-f36c8bd4cc23'),
       UUID('2e9abe7c-0c53-4a7d-816b-875db949e3af'),
       UUID('4f4e756f-e6da-48a9-af0a-0ee6bdb8f4ee'),
       UUID('5aac3e0c-27c7-4780-ad80-dca8f587bd27'),
       UUID('6294b38d-2599-4446-baf3-cd1d7f9f43bd'),
       UUID('754aa321-0039-417c-9717-f794f97ced4c'),
       UUID('78c9c3e0-0cee-11ea-9726-f9cd0ffcd440'),
       UUID('7b70827f-1b59-48f6-ae51-6d59acc76912'),
       UUID('9f70448d-35fc-4555-b7f1-f043c71673a7'),
       UUID('f0bff2c3-4fd2-4182-b1a7-61aa1fb135aa')], dtype=object)

In [42]:
myQuery = """
WITH coefs_obj AS (
    SELECT 
        objects.full_name AS Наименование_ОС,
        objects.construction_object_id,
        stages.title AS Стадия,
        sbcv.variable AS Переменная,
        sbcv.value AS Значение
    FROM "validator".calcp.system_balanced_coefficient_variable sbcv
    LEFT JOIN "validator".cp.construction_object objects 
        ON objects.construction_object_id = sbcv.construction_object_id
    LEFT JOIN "validator".bim.stages stages 
        ON stages.stage_id = sbcv.stage_id
)
SELECT 
    construction_object_id,
    Наименование_ОС,
    Переменная,
    MAX(CASE WHEN Стадия = 'Архпрограмма' THEN Значение END) AS Архпрограмма,
    MAX(CASE WHEN Стадия = 'Концепция планировок' THEN Значение END) AS КонцепцияПланировок,
    MAX(CASE WHEN Стадия = 'Стадия П' THEN Значение END) AS СтадияП,
    MAX(CASE WHEN Стадия = 'Стадия РД' THEN Значение END) AS СтадияРД
FROM coefs_obj
GROUP BY 
    construction_object_id, 
    Наименование_ОС, 
    Переменная
ORDER BY Наименование_ОС, Переменная ASC
"""

# Выполнение запроса
df_coefs = pd.read_sql_query(myQuery, con=engine)[['construction_object_id','Наименование_ОС','Переменная','КонцепцияПланировок']]
df_coefs

,construction_object_id,Наименование_ОС,Переменная,КонцепцияПланировок
0,cf6d6d80-4a13-11e9-936e-1f1fc17436cd,1А Первомайская 01 (МФК),V_B_PARK,487.76
1,cf6d6d80-4a13-11e9-936e-1f1fc17436cd,1А Первомайская 01 (МФК),V_B_DOM,30351.80
2,cf6d6d80-4a13-11e9-936e-1f1fc17436cd,1А Первомайская 01 (МФК),V_ZK,12675.45
3,cf6d6d80-4a13-11e9-936e-1f1fc17436cd,1А Первомайская 01 (МФК),S_F,7756.03
4,cf6d6d80-4a13-11e9-936e-1f1fc17436cd,1А Первомайская 01 (МФК),S_NVF,3466.61
...,...,...,...,...
20527,1215ab54-a821-4b18-9bba-e2ebc48b107c,Яргород 32/КМ,SFA_MM,NaN
20528,1215ab54-a821-4b18-9bba-e2ebc48b107c,Яргород 32/КМ,N_MM,NaN
20529,1215ab54-a821-4b18-9bba-e2ebc48b107c,Яргород 32/КМ,RATIO_DEPENDENT_MM,NaN
20530,1215ab54-a821-4b18-9bba-e2ebc48b107c,Яргород 32/КМ,HEATING_DEVICE_COUNT,NaN
20531,1215ab54-a821-4b18-9bba-e2ebc48b107c,Яргород 32/КМ,HEATING_DEVICE_POWER,NaN

In [47]:
df_tower_coefs = df_coefs[df_coefs['construction_object_id'].isin(objects_with_towers)]
df_pivoted_coef = df_tower_coefs.pivot_table(
    index=['construction_object_id', 'Наименование_ОС'], 
    columns='Переменная', 
    values='КонцепцияПланировок',
    aggfunc='max'
).reset_index()
df_pivoted_coef[['construction_object_id','Наименование_ОС','K1K','K1P','K1TE','K1ZH_KL','K2','N_KV','SFAKV','KB']]

KeyError: "['KB'] not in index"